/**
 * Static Material Category Mapping
 *
 * Maps material tickers to their category slugs.
 * Source: PrUnderground database (synced from FIO API)
 *
 * Categories match FIO's CategoryName field, normalized to slug format.
 */

export const MATERIAL_CATEGORIES: Record<string, string> = {
  // Agricultural Products
  ALG: 'agricultural-products',
  BEA: 'agricultural-products',
  CAF: 'agricultural-products',
  FOD: 'agricultural-products',
  GRA: 'agricultural-products',
  GRN: 'agricultural-products',
  HCP: 'agricultural-products',
  HER: 'agricultural-products',
  HOP: 'agricultural-products',
  MAI: 'agricultural-products',
  MTP: 'agricultural-products',
  MUS: 'agricultural-products',
  NUT: 'agricultural-products',
  PIB: 'agricultural-products',
  PPA: 'agricultural-products',
  RCO: 'agricultural-products',
  RSI: 'agricultural-products',
  VEG: 'agricultural-products',
  VIT: 'agricultural-products',

  // Alloys
  ALR: 'alloys',
  AST: 'alloys',
  BGO: 'alloys',
  BOS: 'alloys',
  BRO: 'alloys',
  FAL: 'alloys',
  FET: 'alloys',
  RGO: 'alloys',
  WAL: 'alloys',
  WRH: 'alloys',

  // Chemicals
  BAC: 'chemicals',
  BL: 'chemicals',
  BLE: 'chemicals',
  CST: 'chemicals',
  DDT: 'chemicals',
  EES: 'chemicals',
  ETC: 'chemicals',
  FLX: 'chemicals',
  IND: 'chemicals',
  JUI: 'chemicals',
  KRE: 'chemicals',
  LCR: 'chemicals',
  NAB: 'chemicals',
  NR: 'chemicals',
  NS: 'chemicals',
  OLF: 'chemicals',
  PFE: 'chemicals',
  REA: 'chemicals',
  SOI: 'chemicals',
  TCL: 'chemicals',
  THF: 'chemicals',

  // Construction Materials
  CMK: 'construction-materials',
  EPO: 'construction-materials',
  GL: 'construction-materials',
  INS: 'construction-materials',
  MCG: 'construction-materials',
  MTC: 'construction-materials',
  NCS: 'construction-materials',
  NFI: 'construction-materials',
  NG: 'construction-materials',
  RG: 'construction-materials',
  SEA: 'construction-materials',

  // Construction Parts
  AEF: 'construction-parts',
  AIR: 'construction-parts',
  DEC: 'construction-parts',
  FC: 'construction-parts',
  FLO: 'construction-parts',
  FLP: 'construction-parts',
  GC: 'construction-parts',
  GV: 'construction-parts',
  LIT: 'construction-parts',
  MGC: 'construction-parts',
  MHL: 'construction-parts',
  PSH: 'construction-parts',
  RSH: 'construction-parts',
  TCS: 'construction-parts',
  TRU: 'construction-parts',
  TSH: 'construction-parts',

  // Construction Prefabs
  ABH: 'construction-prefabs',
  ADE: 'construction-prefabs',
  ASE: 'construction-prefabs',
  ATA: 'construction-prefabs',
  BBH: 'construction-prefabs',
  BDE: 'construction-prefabs',
  BSE: 'construction-prefabs',
  BTA: 'construction-prefabs',
  HSE: 'construction-prefabs',
  LBH: 'construction-prefabs',
  LDE: 'construction-prefabs',
  LSE: 'construction-prefabs',
  LTA: 'construction-prefabs',
  RBH: 'construction-prefabs',
  RDE: 'construction-prefabs',
  RSE: 'construction-prefabs',
  RTA: 'construction-prefabs',

  // Consumable Bundles (no specific color - uses default)
  CBU: 'consumable-bundles',
  EBU: 'consumable-bundles',
  PBU: 'consumable-bundles',
  SBU: 'consumable-bundles',
  TBU: 'consumable-bundles',

  // Consumables (Basic)
  DW: 'consumables-basic',
  EXO: 'consumables-basic',
  FIM: 'consumables-basic',
  HMS: 'consumables-basic',
  HSS: 'consumables-basic',
  LC: 'consumables-basic',
  MEA: 'consumables-basic',
  MED: 'consumables-basic',
  OVE: 'consumables-basic',
  PDA: 'consumables-basic',
  PT: 'consumables-basic',
  RAT: 'consumables-basic',
  SCN: 'consumables-basic',
  WS: 'consumables-basic',

  // Consumables (Luxury)
  ALE: 'consumables-luxury',
  COF: 'consumables-luxury',
  GIN: 'consumables-luxury',
  KOM: 'consumables-luxury',
  NST: 'consumables-luxury',
  PWO: 'consumables-luxury',
  REP: 'consumables-luxury',
  SC: 'consumables-luxury',
  VG: 'consumables-luxury',
  WIN: 'consumables-luxury',

  // Drones
  CCD: 'drones',
  DCH: 'drones',
  DRF: 'drones',
  RED: 'drones',
  SDR: 'drones',
  SRD: 'drones',
  SUD: 'drones',

  // Electronic Devices
  AAR: 'electronic-devices',
  AWF: 'electronic-devices',
  BID: 'electronic-devices',
  BMF: 'electronic-devices',
  BSC: 'electronic-devices',
  BWS: 'electronic-devices',
  HD: 'electronic-devices',
  HOG: 'electronic-devices',
  HPC: 'electronic-devices',
  MHP: 'electronic-devices',
  RAD: 'electronic-devices',
  SAR: 'electronic-devices',

  // Electronic Parts
  CD: 'electronic-parts',
  DIS: 'electronic-parts',
  FAN: 'electronic-parts',
  MB: 'electronic-parts',
  MPC: 'electronic-parts',
  PCB: 'electronic-parts',
  RAM: 'electronic-parts',
  ROM: 'electronic-parts',
  SEN: 'electronic-parts',
  TPU: 'electronic-parts',
  TRA: 'electronic-parts',

  // Electronic Pieces
  BCO: 'electronic-pieces',
  BGC: 'electronic-pieces',
  CAP: 'electronic-pieces',
  HCC: 'electronic-pieces',
  LDI: 'electronic-pieces',
  MFK: 'electronic-pieces',
  MWF: 'electronic-pieces',
  SFK: 'electronic-pieces',
  SWF: 'electronic-pieces',
  TRN: 'electronic-pieces',

  // Electronic Systems
  ACS: 'electronic-systems',
  ADS: 'electronic-systems',
  CC: 'electronic-systems',
  COM: 'electronic-systems',
  CRU: 'electronic-systems',
  FFC: 'electronic-systems',
  LIS: 'electronic-systems',
  LOG: 'electronic-systems',
  STS: 'electronic-systems',
  TAC: 'electronic-systems',
  WR: 'electronic-systems',

  // Elements
  BE: 'elements',
  C: 'elements',
  CA: 'elements',
  CL: 'elements',
  ES: 'elements',
  I: 'elements',
  MG: 'elements',
  NA: 'elements',
  S: 'elements',
  TA: 'elements',
  TC: 'elements',
  ZR: 'elements',

  // Energy Systems
  CBL: 'energy-systems',
  CBM: 'energy-systems',
  CBS: 'energy-systems',
  POW: 'energy-systems',
  SOL: 'energy-systems',
  SP: 'energy-systems',

  // Fuels
  FF: 'fuels',
  SF: 'fuels',
  VF: 'fuels',

  // Gases
  AMM: 'gases',
  AR: 'gases',
  F: 'gases',
  H: 'gases',
  HE: 'gases',
  HE3: 'gases',
  KR: 'gases',
  N: 'gases',
  NE: 'gases',
  O: 'gases',

  // Infrastructure (no specific color - uses default)
  GWS: 'infrastructure',
  PFG: 'infrastructure',
  SDM: 'infrastructure',
  SPT: 'infrastructure',
  SST: 'infrastructure',
  TOR: 'infrastructure',
  TRS: 'infrastructure',

  // Liquids
  BTS: 'liquids',
  H2O: 'liquids',
  HEX: 'liquids',
  LES: 'liquids',

  // Medical Equipment (no specific color - uses default)
  ADR: 'medical-equipment',
  BND: 'medical-equipment',
  PK: 'medical-equipment',
  SEQ: 'medical-equipment',
  STR: 'medical-equipment',
  TUB: 'medical-equipment',

  // Metals
  AL: 'metals',
  AU: 'metals',
  CU: 'metals',
  FE: 'metals',
  LI: 'metals',
  RE: 'metals',
  SI: 'metals',
  STL: 'metals',
  TI: 'metals',
  W: 'metals',

  // Minerals
  BER: 'minerals',
  BOR: 'minerals',
  BRM: 'minerals',
  CLI: 'minerals',
  GAL: 'minerals',
  HAL: 'minerals',
  LST: 'minerals',
  MAG: 'minerals',
  MGS: 'minerals',
  SCR: 'minerals',
  TAI: 'minerals',
  TCO: 'minerals',
  TS: 'minerals',
  ZIR: 'minerals',

  // Ores
  ALO: 'ores',
  AUO: 'ores',
  CUO: 'ores',
  FEO: 'ores',
  LIO: 'ores',
  REO: 'ores',
  SIO: 'ores',
  TIO: 'ores',

  // Plastics
  DCL: 'plastics',
  DCM: 'plastics',
  DCS: 'plastics',
  PE: 'plastics',
  PG: 'plastics',
  PSL: 'plastics',
  PSM: 'plastics',
  PSS: 'plastics',

  // Ship Engines
  AEN: 'ship-engines',
  AFP: 'ship-engines',
  AFR: 'ship-engines',
  ANZ: 'ship-engines',
  BFP: 'ship-engines',
  BFR: 'ship-engines',
  CHA: 'ship-engines',
  ENG: 'ship-engines',
  FIR: 'ship-engines',
  FSE: 'ship-engines',
  GCH: 'ship-engines',
  GEN: 'ship-engines',
  GNZ: 'ship-engines',
  HNZ: 'ship-engines',
  HPR: 'ship-engines',
  HTE: 'ship-engines',
  HYR: 'ship-engines',
  LFE: 'ship-engines',
  LFP: 'ship-engines',
  MFE: 'ship-engines',
  NOZ: 'ship-engines',
  QCR: 'ship-engines',
  RAG: 'ship-engines',
  RCS: 'ship-engines',
  RCT: 'ship-engines',
  SFE: 'ship-engines',
  VOE: 'ship-engines',
  VOR: 'ship-engines',

  // Ship Kits
  HCB: 'ship-kits',
  LCB: 'ship-kits',
  LFL: 'ship-kits',
  LSL: 'ship-kits',
  MCB: 'ship-kits',
  MFL: 'ship-kits',
  MSL: 'ship-kits',
  SCB: 'ship-kits',
  SFL: 'ship-kits',
  SSL: 'ship-kits',
  TCB: 'ship-kits',
  VCB: 'ship-kits',
  VFT: 'ship-kits',
  VSC: 'ship-kits',
  WCB: 'ship-kits',

  // Ship Parts
  AGS: 'ship-parts',
  AHP: 'ship-parts',
  ATP: 'ship-parts',
  BGS: 'ship-parts',
  BHP: 'ship-parts',
  HAM: 'ship-parts',
  HHP: 'ship-parts',
  LHP: 'ship-parts',
  NV1: 'ship-parts',
  NV2: 'ship-parts',
  RHP: 'ship-parts',
  SSC: 'ship-parts',
  THP: 'ship-parts',

  // Ship Shields
  APT: 'ship-shields',
  ARP: 'ship-shields',
  AWH: 'ship-shields',
  BPT: 'ship-shields',
  BRP: 'ship-shields',
  BWH: 'ship-shields',
  SRP: 'ship-shields',

  // Software Components
  BAI: 'software-components',
  LD: 'software-components',
  MLI: 'software-components',
  NF: 'software-components',
  SA: 'software-components',
  SAL: 'software-components',
  WM: 'software-components',

  // Software Systems
  IDC: 'software-systems',
  IMM: 'software-systems',
  SNM: 'software-systems',
  WAI: 'software-systems',

  // Software Tools
  DA: 'software-tools',
  DD: 'software-tools',
  DV: 'software-tools',
  EDC: 'software-tools',
  NN: 'software-tools',
  OS: 'software-tools',

  // Textiles
  CF: 'textiles',
  COT: 'textiles',
  CTF: 'textiles',
  KV: 'textiles',
  NL: 'textiles',
  SIL: 'textiles',
  TK: 'textiles',

  // Unit Prefabs
  BR1: 'unit-prefabs',
  BR2: 'unit-prefabs',
  BRS: 'unit-prefabs',
  BSU: 'unit-prefabs',
  CPU: 'unit-prefabs',
  CQL: 'unit-prefabs',
  CQM: 'unit-prefabs',
  CQS: 'unit-prefabs',
  CQT: 'unit-prefabs',
  DOU: 'unit-prefabs',
  FUN: 'unit-prefabs',
  HAB: 'unit-prefabs',
  LU: 'unit-prefabs',
  RDL: 'unit-prefabs',
  RDS: 'unit-prefabs',
  SU: 'unit-prefabs',
  TCU: 'unit-prefabs',
  WOR: 'unit-prefabs',

  // Utility (no specific color - uses default)
  OFF: 'utility',
  SUN: 'utility',
  UTS: 'utility',
};
