/**
 * Generates assets/fonts.css with base64 data-URL @font-face rules for IBM Plex.
 *
 * Why data URLs: APXM's UI is injected into a Shadow DOM with
 * `cssInjectionMode: 'ui'`. A `url('/fonts/x.woff2')` in that injected sheet
 * resolves against the PAGE origin (apex.prosperousuniverse.com), not the
 * extension, so it 404s; the web_accessible_resources + runtime.getURL route is
 * historically flaky on Orion (WebKit's partial WebExtension reimplementation).
 * Inlining the woff2 as data: URLs is origin-independent and renders identically
 * on Chrome / Firefox / Orion.
 *
 * Source files come from the @fontsource packages (OFL-licensed, latin subset).
 * Re-run after changing the weight list or bumping the font packages:
 *   node scripts/gen-fonts.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// The weights actually used by the Retro Terminal screen style:
//   Sans 400 (body) / 600 (titles, names)
//   Mono 400 (data) / 600 (labels, active states) / 700 (codes, buttons)
const FACES = [
  { family: 'IBM Plex Sans', weight: 400, pkg: 'ibm-plex-sans', file: 'ibm-plex-sans-latin-400-normal.woff2' },
  { family: 'IBM Plex Sans', weight: 600, pkg: 'ibm-plex-sans', file: 'ibm-plex-sans-latin-600-normal.woff2' },
  { family: 'IBM Plex Mono', weight: 400, pkg: 'ibm-plex-mono', file: 'ibm-plex-mono-latin-400-normal.woff2' },
  { family: 'IBM Plex Mono', weight: 600, pkg: 'ibm-plex-mono', file: 'ibm-plex-mono-latin-600-normal.woff2' },
  { family: 'IBM Plex Mono', weight: 700, pkg: 'ibm-plex-mono', file: 'ibm-plex-mono-latin-700-normal.woff2' },
];

const blocks = FACES.map(({ family, weight, pkg, file }) => {
  const path = join(root, 'node_modules', '@fontsource', pkg, 'files', file);
  const b64 = readFileSync(path).toString('base64');
  return `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url(data:font/woff2;base64,${b64}) format('woff2');
}`;
});

const header = `/* GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
 * IBM Plex Sans + Mono (latin subset, OFL) inlined as base64 data URLs so the
 * faces load inside APXM's Shadow DOM overlay on Chrome / Firefox / Orion
 * without web_accessible_resources. Re-run: node scripts/gen-fonts.mjs */\n`;

writeFileSync(join(root, 'assets', 'fonts.css'), `${header}\n${blocks.join('\n\n')}\n`);

const bytes = FACES.reduce(
  (n, { pkg, file }) => n + readFileSync(join(root, 'node_modules', '@fontsource', pkg, 'files', file)).length,
  0
);
console.log(`Wrote assets/fonts.css — ${FACES.length} faces, ${(bytes / 1024).toFixed(1)} KB raw woff2`);
