// Re-export bridge types from shared definition
export type {
  ApxmBridgeMessage,
  ApxmHelloMessage,
  ApxmHelloAckMessage,
  ApxmInitMessage,
  ApxmUpdateMessage,
  ApxmBufferCommandMessage,
  ApxmScreenSwitchMessage,
  ApxmScreenAssignMessage,
  BridgeSnapshot,
  BridgeUpdate,
  BridgeEntityType,
  SiteSummary,
  ShipSummary,
  FlightSummary,
  CargoItem,
  FlightSegmentSummary,
  StorageSummary,
  ProductionSummary,
  WorkforceSummary,
  ContractSummary,
  CurrencyAmount,
  ScreenInfo,
} from '@apxm/bridge';
